image: debian/testing
packages:
  - emacs-nox
  - shellcheck
secrets:
  - 15e4b50e-f2ee-45eb-a6c3-a9502765f740
sources:
  - git@git.sr.ht:~llewxamris/.config
tasks:
  - build: |
        cd .config/ || exit 1
        make all
  - verify: |
        cd .config/dist || exit 1

        shellcheck \
            --exclude=SC1090,SC1091,SC2034 \
            --shell=bash \
            --severity=warning \
            bash-profile.bash bashrc.bash

        shellcheck \
            --shell=sh \
            --severity=warning \
            profile.sh
  - mirror: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cd .config/ || exit 1
        git remote add github git@github.com:Llewxamris/.config.git
        git push --tags github HEAD:master

triggers:
  - action: email
    condition: always
    to: Maxwell Haley <maxwell.r.haley@gmail.com>
