# -*- org-src-preserve-indentation: t; org-edit-src-content-indentation: 0; -*-
#+TITLE: Alacritty Configuration
#+SUBTITLE: Configuration file for the Alacritty terminal emulator
#+AUTHOR: Maxwell Haley
#+EMAIL: maxwell.r.haley@gmail.com
#+PROPERTY: header-args:yaml :tangle dist/alacritty.yml :mkdirp yes
#  LocalWords: Alacritty Iosevka Leuven

* Preface
#+BEGIN_SRC yaml
#   ___  _                 _ _   _
#  / _ \| |               (_) | | |
# / /_\ \ | __ _  ___ _ __ _| |_| |_ _   _
# |  _  | |/ _` |/ __| '__| | __| __| | | |
# | | | | | (_| | (__| |  | | |_| |_| |_| |
# \_| |_/_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                     __/ |
#                                    |___/
#+END_SRC

* The Window
	The ~window~ collection defines how Alacritty is drawn to the screen. I add a
	bit of padding between the sides of the window and the terminal. Without it,
	the text is uncomfortably close to the edge of the monitor.

#+BEGIN_SRC yaml
window:
  padding:
    x: 5
  dynamic_padding: true # Adds a bit more space in some situations
  startup_mode: Maximized
#+END_SRC

* Fonts
Configure the use of the Go Mono font. As well, disable converting all bold
text to use the bright colours.

#+BEGIN_SRC yaml
font:
  normal:
    family: Go Mono
    style: Regular

  bold:
    family: Go Mono
    style: Bold

  italic:
    family: Go Mono
    style: Italic, Regular

  size: 12

draw_bold_text_with_bright_colors: false
#+END_SRC

* Colours
	My colours scheme is derived from the [[https://github.com/fniessen/emacs-leuven-theme][Leuven Theme]] for Emacs. For some
	elements (e.g. primary background and foreground colours) it was obvious which
	Leuven face was needed. Other colours were not as simple. Brighter colours,
	like cyan or yellow, are used mostly by Leuven as background or highlight
	faces. This makes them unusable for text colour, especially if it is directly
	against the pure white background.

	I have annotated each colour in this configuration with a comment declaring
	which Leuven color class or custom face I lifted the value from.

 #+BEGIN_SRC yaml
colors:
  primary:
    background: '0xFFFFFF' # default :background
    foreground: '0x333333' # default :foreground

  cursor:
    text: '0x333333' # default :foreground
    cursor: '0x21BDFF' # cursor :background

  selection:
    background: '0x8ED3FF' # region :background

  normal:
    black:   '0x000000'
    red:     '0xFE251E' # flycheck-error :underline :color
    green:   '0x008000' # string :foreground
    yellow:  '0xFFA500' # warning :foreground
    blue:    '0x000088' # code-block :foreground
    magenta: '0x6434A3' # font-lock-type-face :foreground
    cyan:    '0x123555' # ol2 :overline
    white:   '0x8D8D84' # font-lock-comment-face :foreground

  bright:
    black:   '0x555555' # org-block-begin-line :foreground
    red:     '0xFF0000' # gnus-group-news-4 :foreground
    green:   '0x158A15' # flycheck-fringe-info :foreground
    yellow:  '0xF4B400' # ???
    blue:    '0x335EA8' # mode-line :box :background
    magenta: '0xBA36A5' # font-lock-variable-name-face :foreground
    cyan:    '0x008ED1' # org-meta-line :foreground
    white:   '0x9A9A9A' # linum :foreground
#+END_SRC

* Mouse
	The only mouse setting I change is to copy selected text to the primary
	clipboard. This way I can select output and quickly paste it elsewhere.
	For example, throwing errors into a search engine.

#+BEGIN_SRC yaml
selection:
  save_to_clipboard: true
#+END_SRC

