# -*- org-src-preserve-indentation: t; org-edit-src-content-indentation: 0; -*-
#+TITLE: Alacritty Configuration
#+SUBTITLE: Configuration file for the Alacritty terminal emulator
#+AUTHOR: Maxwell Haley
#+EMAIL: maxwell.r.haley@gmail.com
#+PROPERTY: header-args:yaml :tangle dist/alacritty.yml :mkdirp yes
#  LocalWords: Alacritty Iosevka Leuven

* Preface
#+BEGIN_SRC yaml
#   ___  _                 _ _   _
#  / _ \| |               (_) | | |
# / /_\ \ | __ _  ___ _ __ _| |_| |_ _   _
# |  _  | |/ _` |/ __| '__| | __| __| | | |
# | | | | | (_| | (__| |  | | |_| |_| |_| |
# \_| |_/_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                     __/ |
#                                    |___/
#+END_SRC

* The Window
	The ~window~ collection defines how Alacritty is drawn to the screen. I add a
	bit of padding between the sides of the window and the terminal. Without it,
	the text is uncomfortably close to the edge of the monitor.

#+BEGIN_SRC yaml
window:
  padding:
    x: 5
  dynamic_padding: true # Adds a bit more space in some situations
  startup_mode: Maximized
#+END_SRC

* Fonts
Configure the use of the Go Mono font. As well, disable converting all bold
text to use the bright colours.

#+BEGIN_SRC yaml
font:
  normal:
    family: Go Mono
    style: Regular

  bold:
    family: Go Mono
    style: Bold

  italic:
    family: Go Mono
    style: Italic, Regular

  size: 12

draw_bold_text_with_bright_colors: false
#+END_SRC

* Colours
I based my colours on the [[https://gitlab.com/dj_goku/modus-themes][Modus Operandi]] theme for Emacs. I find it colourful
enough to not be visually boring, but not too colourful to be visually noisy. If
the source of the colour is non-obvious, then it has a comment stating what the
source was.

 #+BEGIN_SRC yaml
colors:
  primary:
    background: '0xFFFFFF' # bg-main
    foreground: '0x000000' # fg-main

  cursor:
    text: '0xFFFFFF'       # bg-main
    cursor: '0x000000'     # bg-main

  selection:
    background: '0xBCBCBC' # bg-region
    foreground: '0x000000' # fg-main

  normal:
    black:   '0x000000'    # fg-main
    red:     '0xA80000'
    green:   '0x005F00'
    yellow:  '0x8B3800'
    blue:    '0x0030A6'
    magenta: '0x721045'
    cyan:    '0x005589'
    white:   '0xF3F1F3'    # bg-alt

  bright:
    black:   '0x424242'    # fg-inactive
    red:     '0xB60000'    # red-intense
    green:   '0x006800'    # green-intense
    yellow:  '0x904200'    # yellow-intense
    blue:    '0x1111EE'    # blue-intense
    magenta: '0x7000E0'    # magenta-intense
    cyan:    '0x205B93'    # cyan-intense
    white:   '0xF8F8F8'    # bg-dim
#+END_SRC

* Mouse
	The only mouse setting I change is to copy selected text to the primary
	clipboard. This way I can select output and quickly paste it elsewhere.
	For example, throwing errors into a search engine.

#+BEGIN_SRC yaml
selection:
  save_to_clipboard: true
#+END_SRC

